//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Mibarim_plusEntities : DbContext
    {
        public Mibarim_plusEntities()
            : base("name=Mibarim_plusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Invite> Invites { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<Trip> Trips { get; set; }
        public virtual DbSet<StationRoute> StationRoutes { get; set; }
        public virtual DbSet<vwDriverTrip> vwDriverTrips { get; set; }
        public virtual DbSet<TelegramMsg> TelegramMsgs { get; set; }
        public virtual DbSet<TelegramUser> TelegramUsers { get; set; }
        public virtual DbSet<PassNotif> PassNotifs { get; set; }
        public virtual DbSet<PassengerRoute> PassengerRoutes { get; set; }
    }
}
