//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invite
    {
        public long InviteId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string InviteCode { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> InviterUserId { get; set; }
        public Nullable<short> InviteType { get; set; }
        public Nullable<long> InviterId { get; set; }
    }
}
