//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassengerRoute
    {
        public long PassRouteId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public long UserId { get; set; }
        public long StationRouteId { get; set; }
        public System.DateTime PassTime { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<short> NotifSeq { get; set; }
    }
}
