//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassNotif
    {
        public long PassNotifId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public long UserId { get; set; }
        public long StationRouteId { get; set; }
        public int NotifStatus { get; set; }
    }
}
