//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelegramUser
    {
        public long TuserId { get; set; }
        public System.DateTime TcreateTime { get; set; }
        public Nullable<int> TbotId { get; set; }
        public long TelegramUserId { get; set; }
        public Nullable<long> UserId { get; set; }
        public string TmsgUserName { get; set; }
        public string TmsgName { get; set; }
        public string TmsgFamily { get; set; }
        public string PhoneNumber { get; set; }
        public string TinviteCode { get; set; }
    }
}
