//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelegramMsg
    {
        public long TmsgId { get; set; }
        public System.DateTime TmsgCreateTime { get; set; }
        public long TuserId { get; set; }
        public int TmsgType { get; set; }
        public string TmsgMessage { get; set; }
        public Nullable<long> ChatId { get; set; }
    }
}
