//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int UserInfoId { get; set; }
        public int UserId { get; set; }
        public string NationalCode { get; set; }
        public byte[] UserPic { get; set; }
        public System.DateTime UserInfoCreateTime { get; set; }
        public bool UserInfoIsDeleted { get; set; }
        public Nullable<System.Guid> UserImageId { get; set; }
        public Nullable<System.Guid> NationalCardImageId { get; set; }
        public Nullable<short> VerifiedLevel { get; set; }
        public Nullable<long> TripId { get; set; }
        public Nullable<int> Smscount { get; set; }
        public Nullable<int> ValidatingTry { get; set; }
        public Nullable<System.Guid> UserUId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
