//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDriverTrip
    {
        public System.DateTime TCreateTime { get; set; }
        public System.DateTime TStartTime { get; set; }
        public short TState { get; set; }
        public short TEmptySeat { get; set; }
        public long DriverRouteId { get; set; }
        public long UserId { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public Nullable<int> Gender { get; set; }
        public string UserName { get; set; }
        public Nullable<System.Guid> UserImageId { get; set; }
        public string CarType { get; set; }
        public string CarColor { get; set; }
        public string CarPlateNo { get; set; }
        public long TripId { get; set; }
        public string SrcMainStName { get; set; }
        public Nullable<long> SrcMainStationId { get; set; }
        public Nullable<decimal> SrcMainStLat { get; set; }
        public Nullable<decimal> SrcMainStLng { get; set; }
        public System.Data.Entity.Spatial.DbGeography SrcMainStGeo { get; set; }
        public string SrcStAdd { get; set; }
        public Nullable<decimal> SrcStLat { get; set; }
        public Nullable<decimal> SrcStlng { get; set; }
        public string DstMainStName { get; set; }
        public Nullable<decimal> DstMainStLat { get; set; }
        public Nullable<decimal> DstMainStLng { get; set; }
        public Nullable<long> DriverPrice { get; set; }
        public Nullable<long> PassPrice { get; set; }
        public Nullable<short> VerifiedLevel { get; set; }
        public long StationRouteId { get; set; }
    }
}
