//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KntuWebHook {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KntuWebHook.messages", typeof(messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت کسب اطلاعات بیشتر و راهنمایی با شماره 
        ///۰۹۳۵۸۶۹۵۷۸۵ لشکری
        ///تماس حاصل کنید
        ///و یا با آی دی تلگرامی
        ///@hamedlq
        ///در تماس باشید
        ///با تشکر.
        /// </summary>
        internal static string ContactSupport {
            get {
                return ResourceManager.GetString("ContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از همسفری‌هات عکس یا فیلم بگیر و با هشتگ #باهم_بریم به اشتراک بذار و لینکش رو بفرست تا ۲۰ امتیاز دریافت کنی. از این راه می‌تونی دوستانت رو هم دعوت کنی تا به تیم تو ملحق شن..
        /// </summary>
        internal static string ContentScore {
            get {
                return ResourceManager.GetString("ContentScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در صورت ثبت مسیر در مبدا یا مقصد مشخص شده در نقشه دو برابر مبلغ سوخت به حساب شما واریز خواهد شد.
        /// </summary>
        internal static string DoublePlan {
            get {
                return ResourceManager.GetString("DoublePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما هنوز امتیازی کسب نکردید
        ///لطفا اپلیکیشن رو از یکی از لینک های زیر دانلود کنید
        ///لینک وبسایت
        ///http://mibarim.com/driver/
        ///کافه بازار
        ///https://cafebazaar.ir/app/com.mibarim.driver/?l=fa
        ///مایکت
        ///https://myket.ir/app/com.mibarim.driver/?lang=fa
        ///لینک مستقیم
        ///http://mibarimapp.com/androidapp/downloaddriver.
        /// </summary>
        internal static string DownloadApp {
            get {
                return ResourceManager.GetString("DownloadApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با روشن کردن سفر در اپلیکیشن، مسافتی که طی می‌کنید محاسبه میشه و پول بنزین این مسیر به اعتبارتون اضافه میشه. وقتی اعتبارتون به صدهزار تومن رسید میتونید از داخل اپلیکیشن درخواست وجه بزنید و ما هم پول بنزینتونو به حسابتون واریز میکنیم. به همین سادگی!!
        ///
        ///مسافت طی شده: {0} کیلومتر
        ///هزینه باک بنزین : {1} تومان.
        /// </summary>
        internal static string GasScore {
            get {
                return ResourceManager.GetString("GasScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تو هم می‌خوای پول بنزینت رو به راحتی دریافت کنی؟ با کد معرفی {0} وارد این بات شو و بگو هر روز چه مسیری رو میری. هر روز مسیرت رو فعال کن تا آخر ماه پول بنزینت به حسابت واریز بشه.
        ///
        ///لینک عضویت:
        ///http://telegram.me/benzinbama_bot.
        /// </summary>
        internal static string InviteMessage {
            get {
                return ResourceManager.GetString("InviteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام بالا حاوی کد معرفی شماست. با ارسال این پیام به دیگران یا انتشار در شبکه‌های اجتماعی و گروه‌های تلگرامی، اگر راننده‌ای رو دعوت کنید که یک ماه مسیرش رو روشن کنه ۳۰ هزارتومان پاداش دریافت می‌کنید. اگر هم مسافری با این کد وارد اپلیکیشن بشه و پنج سفر انجام بده شما هم ده هزار تومان وجه نقد دریافت می‌کنید..
        /// </summary>
        internal static string InviteScore {
            get {
                return ResourceManager.GetString("InviteScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با روشن کردن اعلان‌ها ساعت‌هایی که دوستانتان اعلام می‌کنند به شما اطلاع داده می‌شود..
        /// </summary>
        internal static string NotifSetting {
            get {
                return ResourceManager.GetString("NotifSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا دکمه ارسال شماره تلفن همراه را فشار دهید👇👇👇👇👇.
        /// </summary>
        internal static string PushShareContact {
            get {
                return ResourceManager.GetString("PushShareContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست برای مسیر {0} لغو شد.
        /// </summary>
        internal static string RequestCanceled {
            get {
                return ResourceManager.GetString("RequestCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کافیه ۲۲ روز در یک ماه مسیر خودت رو روشن کنی تا حتی بدون رزرو شدن صندلی‌هات هزینه روزانه سوخت‌ات رو دریافت کنی. برای این کار روی گزینه زیر بزن و ساعت حرکت‌ات رو برای ۲۴ ساعت آینده مشخص کن. حالا کافیه اگر کسی صندلی‌ات رو رزرو کرد در ساعتی که تعیین کردی در ایستگاه باشی.
        ///
        ///روز آغازین دوره شما: {0}
        ///تعداد روزهایی که مسیرت رو روشن کردی: {1}
        ///تعداد روزهایی که لازمه مسیرت رو روشن کنی تا پاداش رو بگیری: {2}.
        /// </summary>
        internal static string RideScore {
            get {
                return ResourceManager.GetString("RideScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روشن کردن مسیر هر روز ۱۰ امتیاز
        ///روشن کردن ۲۰ روز در یک ماه ۲۰۰ امتیاز
        ///دعوت دوستان به بات ۴۰ امتیاز
        ///دعوت راننده و روشن کردن مسیر توسط آن‌ها هر روز ۵۰ امتیاز 
        ///دعوت راننده و زدن گل توسط آن‌ها ۴۰۰ امتیاز 
        ///دعوت مسافر و انجام سفر ۳۰ امتیاز.
        /// </summary>
        internal static string ScoreHelp {
            get {
                return ResourceManager.GetString("ScoreHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بر روی آیکون افزودن مسیر کلیک کنید.
        /// </summary>
        internal static string Statement1 {
            get {
                return ResourceManager.GetString("Statement1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از بین مسیرهای تعریف شده مسیری که روزانه طی می‌کنید را انتخاب کنید.
        /// </summary>
        internal static string Statement2 {
            get {
                return ResourceManager.GetString("Statement2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایستگاه مبدا مکانی است که باید برای سوار کردن هم‌مسیران در آن منتظر بمانید.
        /// </summary>
        internal static string Statement3 {
            get {
                return ResourceManager.GetString("Statement3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هر روز از ۲۴ ساعت تا یک ربع قبل از حرکت از مبدا می‌توانید زمان حرکت خود را به دیگران اعلام نمایید..
        /// </summary>
        internal static string Statement4 {
            get {
                return ResourceManager.GetString("Statement4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان حرکت زمانی است که شما باید در ایستگاه مبدا که مشخص کرده‌اید منتظر هم‌مسیران بمانید.
        /// </summary>
        internal static string Statement5 {
            get {
                return ResourceManager.GetString("Statement5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد صندلی خالی که می‌توان رزرو کرد را مشخص کنید..
        /// </summary>
        internal static string Statement6 {
            get {
                return ResourceManager.GetString("Statement6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در صورت رزرو صندلی خودرو توسط هم‌مسیر، نیم ساعت قبل از سفر با پیامک به شما اطلاع داده می‌شود..
        /// </summary>
        internal static string Statement7 {
            get {
                return ResourceManager.GetString("Statement7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در زمان سفر در صورت رزرو شدن صندلی خودرو به ایستگاهی که مشخص شده بروید و مکان‌نما(Gps) تلفن همراه خود را روشن کنید تا هم‌مسیران سریع‌تر بتوانند شما را پیدا کنند و بر روی دکمه منتظر هم‌مسیران هستم کلیک کنید تا فرآیند انتقال وجه نیم ساعت پس از شروع حرکت انجام شود.پس از ۵ دقیقه انتظار می‌توانید حرکت کنید..
        /// </summary>
        internal static string Statement8 {
            get {
                return ResourceManager.GetString("Statement8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در هر زمان که می‌خواهید می‌توانید از بخش اعتبار با وارد کردن شماره شبای بانکی خود درخواست تصفیه حساب را بزنید تا در کمتر از ۲۴ ساعت مبلغ به حساب شما منتقل شود..
        /// </summary>
        internal static string Statement9 {
            get {
                return ResourceManager.GetString("Statement9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر {0}
        ///در اینجا ساعت هایی که دیگران برای این مسیر ثبت کرده‌اند مشاهده می‌کنید.
        ///اگر این زمان‌ها متناسب با زمان شما است انتخاب کنید در غیراینصورت زمان متناسب خودتان را در فرمت ۲۴ ساعته وارد کنید(یعنی صبح ۷:۳۰ و بعدازظهر ۱۹:۳۰).
        /// </summary>
        internal static string TimeInfo {
            get {
                return ResourceManager.GetString("TimeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان درخواستی شما برای این مسیر ثبت شد و به اطلاع همه دوستان خواهد رسید
        ///در صورت انصراف حتما درخواست را لغو کنید تا باعث سردرگمی سایر دوستان نشود👇👇👇👇👇.
        /// </summary>
        internal static string TimeSet {
            get {
                return ResourceManager.GetString("TimeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان درخواستی شما برای این مسیر ثبت شد و به اطلاع همه دوستان خواهد رسید
        ///برای هماهنگی با شما لطفا حتما دکمه ارسال شماره تلفن همراه را فشار دهید👇👇👇👇👇
        ///در صورت انصراف حتما درخواست را لغو کنید تا باعث سردرگمی سایر دوستان نشود👇👇👇👇👇.
        /// </summary>
        internal static string TimeSetWithPhone {
            get {
                return ResourceManager.GetString("TimeSetWithPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با دانلود اپلیکیشن می‌بریم می‌تونی همسفرهای مطمئنی پیدا کنی و هر روز با هزینه پایین بین خانه تا محل کار جابجا بشی. با هربار سفر ۳۰ امتیاز دریافت می‌کنی. همین طور اگه هر کدوم از هم تیمی‌هات هم سفر کنند ۴۰ امتیاز و اگر هم تیمی‌هات کسی رو جابجا کنند ۵۰ امتیاز می‌گیری.
        /// </summary>
        internal static string TripScores {
            get {
                return ResourceManager.GetString("TripScores", resourceCulture);
            }
        }
    }
}
